### ISSUE TITLE
Feature Request: pz7ip package for bulk wallet compression with aes256 encryption

### ISSUE THREAD

**Issue by KeithNel** [bitkey/bitkey#11]
The p7zip package (http://p7zip.sourceforge.net/)  provides a simple and cross platform method for compression with AES256 encryption. 

Use case:  Bulk wallet compression with aes256 encryption, or any other wallet files that are to be transported.

Of course it is already possible to do this in with bzip then openssl, p7zip only provides slightly more convienience especially for those that must regularly send wallet files to non linux systems.

**Comment by JedMeister** [comment]
It looks like it's in the [Debian repos](https://packages.debian.org/search?suite=jessie&searchon=names&keywords=p7zip) so you could just add it to the plan (or more correctly one of the plans...). Actually the [apps plan](https://github.com/bitkey/bitkey/blob/master/plan/apps) looks like the one...

I'm not sure if anyone has tested building it on Jessie yet, but the v14.0RC1 TKLDev is available for download so if you are keen you could check it out!

**Comment by JedMeister** [comment]
Closed by https://github.com/bitkey/bitkey/commit/c96485b9bfb752a102b5d8728572a82b5b9f7a0f
