### ISSUE TITLE
any news of this project? electrum 2.x?

### ISSUE THREAD

**Issue by tbergeron** [bitkey/bitkey#12]
Hi!

I just found out about BitKey and been using it for over a week. So far it works as expected, I'm blown away that there's not much popularity in that kind of project knowing how infected the common PC is.

I'd like to know:

1) is the project is still alive and in development?
2) any intentions of upgrading to Electrum 2.x?
3) would you still suggest using BitKey to be your main bitcoin wallet over a long period of time?

Thanks a lot and keep up the amazing work!

**Comment by JedMeister** [comment]
Hi,

I am not very familiar with BitKey (or Bitcoin in general) but I work with the devs (Alon & Liraz). We do [TurnKey Linux](https://www.turnkeylinux.org/).

Both Alon and Liraz use Bitcoins and this was a side project for them. There has been a ton of work going on within TurnKey so BitKey really hasn't got the love it deserves.

To explicitly answer your questions:
1) yes but it is currently awaiting time/energy required for update
2) Probably most (if not all) components would be updated in an updated release (whenever that might happen)
3) TBH I can't answer that question. However, whilst having newer versions would make it better (and possibly more secure too) it should still be useful and relatively secure. Certainly much more secure than your average Windows machine!

**Comment by tbergeron** [comment]
Hi and thanks for your quick answer!

I totally understand that BitKey isn't TurnKey's main project. I just wondered if the project was seen as stable enough to be used in real life scenarios, glad to read that it is even if it's not updated which is fine IMO. Sometimes updates fix bugs and create new ones hehe

I'll keep using it and will report if anything bad happens! :+1: 

Thanks again!
