### ISSUE TITLE
Update BitKey to v14.x/Debian Jessie base

### ISSUE THREAD

**Issue by JedMeister** [bitkey/bitkey#14]
As the title suggests, BitKey needs updating to the v14.x (Debian Jessie) TurnKey Linux base. See entry on main TurnKey Tracker: https://github.com/turnkeylinux/tracker/issues/614

**Comment by JedMeister** [comment]
Todos prior to release:

 - [ ] update browser defaults (so that they work as they used to) https://github.com/bitkey/bitkey/pull/15#discussion-diff-66208857 & https://github.com/bitkey/bitkey/pull/15#discussion-diff-66209161
 - [ ] reinstate firstboot secupdates https://github.com/bitkey/bitkey/pull/15#discussion-diff-66208901
 - [ ] some mechanism to check the 9non-Debian) included software https://github.com/bitkey/bitkey/pull/15#discussion-diff-66209450

**Comment by lirazsiri** [comment]
I verified the non Debian software manually. Doing this automatically would be better but more work would be required. I'm going to push out a new version soon.
