### ISSUE TITLE
Add Ian Coleman's BIP39 mnemonic code converter tool

### ISSUE THREAD

**Issue by lirazsiri** [bitkey/bitkey#21]
Planning on adding this tool to the next version of BitKey:
https://iancoleman.github.io/bip39/

Comments welcome.

Rational:

- Supports various methods of generating HD wallet keys
- Supports manual entropy entry via dice rolls, a stack of cards or hexademical, with suitable warnings. 
- Manual entropy mode embeds an entropy measuring tool, is deterministic and would not be vulnerable to a broken CSPRNG. 
- Supports BIP39 with plausibly deniable passphrases. So you can back them up on paper and still get some protection + defense from a $5 wrench attack.

I'm hoping Warpwallet merged BIP39 support soon, but even if they don't it would still be possible to chain these tools by hand:
from warpwallet:

1) generate warpwallet, copy the privacy key
2) in a command line convert private key into hex: bx-base58-decode $warpwallet-private-key
3) mnemonic code converter, provide entropy (identifies as hex)
4) add short passphrase - write down seed without passphrase

**Comment by lirazsiri** [comment]
Related issue:

https://github.com/bitkey/bitkey/issues/26

**Comment by richsmith92** [comment]
@lirazsiri Do I understand the usecase right?

1. I come up with a passphrase which I can easily remember but complex enough to bruteforce
2. Salt it with my email and with warpwallet create the private key
3. Use it as entropy for Coleman's `bip39` tool and obtain the seed 

Now I have a seed from BIP39 wordlist (not necessarily 12 words). With Electrum I can recover the wallet from it.

Even better, now I can share the seed with my grandma, and she'll be able to recover the wallet. If I just gave her the original passphrase, she wouldn't be able to follow steps 1-3.

**Comment by lirazsiri** [comment]
Yes that's exactly the use case. Both the salt and a passphrase are needed
to recover the HD seed

**Comment by Boristka** [comment]
Hi.
I have my seed phrase of a HD wallet i created on bither in 2016.

I also have the adress i used.

When i try any "recover wallet with mnmonic" it gives me an empty wallet...
While, i can see my transactions and my 135 mBTC left when i put the adress in a watch only wallet..

I tried also to get an private key with the https://iancoleman.github.io/bip39/

But i dont find my adress on the list...

Can anyone help me ?

**Comment by richsmith92** [comment]
@Boristka you better address this to Bither support. IIRC Bitkey has nothing to do with Bither.

**Comment by estevaocm** [comment]
Added in my fork at https://github.com/estevaocm/bitkey

**Comment by estevaocm** [comment]
As my fork has been merged into the Bitkey community branch, I believe we can close this issue.
