### ISSUE TITLE
E. Package 'xresprobe' has no installation candidate

### ISSUE THREAD

**Issue by bubble501** [bitkey/bitkey#35]
When I build it from source according the instruction in document, i met the error:
E. Package 'xresprobe' has no installation candidate.

any idea of how to fix this?

**Comment by JedMeister** [comment]
Hi @bubble501 

I see that you've closed this. Is that because you worked it out? Or did you just close it accidentally?

**Comment by bubble501** [comment]
Hello @JedMeister 

I had worked it out, I met this problem when i use this [vagrant 
 box ](https://vagrantcloud.com/rgoldman/boxes/tkldev).  I found that that this box has been created 1 year ago, so I try the latest tkldev image directly using virtualbox and it works perfectly. Thanks for the awesome works.

**Comment by JedMeister** [comment]
Ah ha! We have been meaning to make official vagrant boxes, but something more important always seems to get in the way...

Glad you got it sorted! :smile:
