### ISSUE TITLE
BIP44 support?

### ISSUE THREAD

**Issue by hjfreyer** [bitkey/bitkey#37]
As far as I can tell, none of the installed apps support [BIP44 wallets](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki). Thoughts?

**Comment by westonal** [comment]
IIRC, the electrum wallet is languishing behind on 2.6, and would be fine if it were on 2.9

**Comment by estevaocm** [comment]
My fork at https://github.com/estevaocm/bitkey includes https://github.com/iancoleman/bip39 which also includes bip 32, 44, 49 and 141.

**Comment by estevaocm** [comment]
My fork has been merged to the community branch.
