### ISSUE TITLE
SEGWIT supported electrum wallet.

### ISSUE THREAD

**Issue by zanderisrael** [bitkey/bitkey#46]
Please update perform an update to bitkey, that adds a newer version of electrum. 
I can help if the main devs don't have time...

**Comment by JedMeister** [comment]
Hey @zanderisrael - we hope to do this sometime soonish, but as BitKey is a side project, I can't give you any timeframe. Having said that, you can rebuild BitKey yourself if you wish.

If you have a look at what @estevaocm is up to in #48, he's actually already got build code to include Electrum 3.0.2 - perhaps you could collaborate with him?

**Comment by estevaocm** [comment]
Now solved in the community branch.
