### ISSUE TITLE
add support for bit2factor (implementation of BIP38)

### ISSUE THREAD

**Issue by alonswartz** [bitkey/bitkey#5]
Suggested by `Chris B` via email.
### Resources
- https://bit2factor.org
- https://github.com/mannkind/bit2factor.org
- https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki

**Comment by lirazsiri** [comment]
bitaddress is also an implementation of BIP38, at least in terms of generating an encrypted paper wallet. bit2factor code is unmaintained, and there doesn't seem to be a terrible amount of interest in the use case it supports, so adding this to BitKey may do more harm than good.
