### ISSUE TITLE
Extended seed

### ISSUE THREAD

**Issue by tuberculo** [bitkey/bitkey#51]
Does Bitkey support extended seed feature in Electrum? I tried to use this feature but couldn't do it.

**Comment by JedMeister** [comment]
Hey @tuberculo - unfortunately, I don't have a clue. Perhaps you required a specific version of Electrum to do that? If you can direct me towards some docs noting what you are trying to do, perhaps I could give you some guidance?

----

FWIW, I work with TurnKey so can give advice and support on general OS stuff (as BitKey is based on TurnKey) but I'm not a BitKey user nor do I personally know anything much about bitcoin or any bitcoin related software. Alon and Liraz do know lots about bitcoin and developed and use BitKey themselves. Unfortunately though, as this is a side project for us, getting their feedback for BitKey related stuff can be a slow process.

**Comment by tuberculo** [comment]
I could not find the documentation about this feature, but it is mentioned here, https://bitcointalk.org/index.php?topic=1672883.0. 
It also says that it was introduced in version 2.7. So, that's the reason Bitkey does not have it, as it uses version 2.6, I believe.

**Comment by JedMeister** [comment]
FWIW, @estevaocm is developing an updated version that includes Electrum 3.x so perhaps you could link up with him and assist with testing and development?

Have a look here: https://github.com/bitkey/bitkey/issues/48#issuecomment-348670180
