### ISSUE TITLE
suggestion to include keepass

### ISSUE THREAD

**Issue by architectdesigner** [bitkey/bitkey#52]

**Comment by tuberculo** [comment]
If I understand it right, one should add "keepassx" to /plan/apps. Is that right?

**Comment by JedMeister** [comment]
@tuberculo - Yes, assuming you want to install the Debian Jessie package `keepassx` (for Debian package info, see [here](https://packages.debian.org/jessie/keepassx)).

**Comment by jeremejazz** [comment]
Or Keepass**xc** https://keepassxc.org
Its development is more active

**Comment by JedMeister** [comment]
@jeremejazz - Yeah that's how Debian works. It's the lack of development which makes it so stable. Security issues are addressed via backported patches and are auto applied at boot. Whilst the version will be older, it's supported without needing to do any extra work (so lighter maintenance costs for us - not that we're doing a very good job of maintenance recently anyway...).

Another factor is that the risk of anything breaking is also extremely small as the Debian security team are very careful about how they backport security patches.

Unless there is a really good reason to not use a Debian package, then that is always going to be the preferred option from our perspective. But by all means if you have a strong rationale why we should use upstream, then feel free to share.

PS sorry for slow reply; bitkey is a side project for us and our main job is currently soaking up everything we can give it...

**Comment by tuberculo** [comment]
Hi @JedMeister. Is it possible to install [jessie-backports](https://packages.debian.org/jessie-backports/keepassx) version?
If it is, how?

**Comment by estevaocm** [comment]
Added keepassx from the jessie repository. May look into the backport in the future.

**Comment by george-viaud** [comment]
KeepassXC may be a better option.  Anecdotally, I find it to be far more well maintained and feature-rich.

**Comment by tuberculo** [comment]
Sure, but maybe it is not possible to install KeepassXC in Bitkey, as Bitkey is based on an very old Debian version.
Keepassx version from backport would already be a great improvement, as the jessie version is very old and cannot read the file format used in the newer versions.

**Comment by estevaocm** [comment]
@tuberculo, I suppose the backport can be installed in Bitkey similarly to how Exodus is. Would have to check out any dependencies and other possible incompatibilities though. This could take a lot more time than my usual wallet updates and javascript app additions, so I won't give a time frame just yet. I was not aware the new version uses a new file format, that indeed complicates usability.

**Comment by estevaocm** [comment]
I could try installing this, maybe it will solve everyone's problems? https://github.com/magkopian/keepassxc-debian/releases
No idea if that version can be trusted, but it's linked at the official site at least.

**Comment by estevaocm** [comment]
Missing dependencies for keepassxc:
libqt5x11extras5 5.1.0
libykpers-1-1 1.12.0

**Comment by estevaocm** [comment]
Got keepassxc working. Some tidying up to do before publishing though. Will commit first to https://github.com/estevaocm/bitkey/ and later merge here.

**Comment by jeremejazz** [comment]
:+1:  glad it does. It has more features and has continuously maintained. not that we need to update always but at least we have those additional features.
