### ISSUE TITLE
A vulnerability has been found in Electrum

### ISSUE THREAD

**Issue by carloslrr** [bitkey/bitkey#55]
A vulnerability has been found in Electrum, and patched in version 3.0.5. You can see it in https://electrum.org 
Please update your software.

**Comment by JedMeister** [comment]
Hi, thanks for this. 

Really sorry for my slow response! We'll certainly look into it ASAP. In the meantime, I'll get in touch with my colleague Alon and get him to have a closer look. If need be, we may need to pull the current image. I'm not sure when we'll be able to republish it.

FWIW, this is really just a side project for us, so it doesn't get the love that it deserves.

**Comment by estevaocm** [comment]
@carloslrr, my fork https://github.com/estevaocm/bitkey/ solves this issue.

**Comment by carloslrr** [comment]
@estevaocm, thank you very much for your response, I'll try it.  :)

**Comment by estevaocm** [comment]
This is fixed in the new community branch.
