### ISSUE TITLE
Create new "community" branch and promote Steven to BitKey community leader.

### ISSUE THREAD

**Issue by JedMeister** [bitkey/bitkey#56]
As most would be aware, BitKey is a side project of TurnKey Linux. Other than the initial development and a few updates here and there over the years, we've done a really poor job of maintaining it! :cry: 

However, the BitKey community was lucky enough that @estevaocm has come along and given the project some love. He rolled up his sleeves, forked the project and has been doing an incredible job to extend BitKey and keep it's components up to date.

Seeing as we're doing such a poor job and he's doing such a great one, I've asked him to join BitKey (in a voluntary capacity, at least for now) as the community leader. :tada: 

What we'll do initially, is add a new "community" branch to BitKey, which will become the "default" branch (what everyone will see when they browse to the repo). "master" will remain the "official" BitKey codebase, but all the action will happen in "community". We'll invite Steven to join the BitKey GitHub organization and give him push and merge access to the community repo and the issues, etc. That will mean that everyone will have the best chance of getting access to the latest code that Steven (and others hopefully) have contributed!

I hope to complete that work this week, but due to constraints it may not happen until next week.

Thanks again for being willing to help us out with this @estevaocm! You my friend, are a legend! :smile:

**Comment by JedMeister** [comment]
I'm closing this now as I'm pretty sure everything is set up good to go! :smile: 

----

Hey @estevaocm - I've now done that and everything should be working as expected. If there is anything I've missed or something isn't working for you, please let me know.

You have full write access to the new `community` branch and can push direct to it. You'll also be able to approve and merge pull requests, although you won't be able to merge into master. 

For good practice though, it would be good to ensure that work you do locally is on a separate (i.e. not `community`) branch. Then before you push back to the community branch, make sure that you do a pull (to pull in any merged pull requests, etc). So assuming that you are have `turnkey` set as your `origin` remote, workflow would look something like this:
```
root@tkldev products/bitkey# git branch
* community
  master
root@tkldev products/bitkey# git checkout -b new-work
Switched to a new branch 'new-work'
root@tkldev products/bitkey# echo > some-work
root@tkldev products/bitkey# git add some-work 
root@tkldev products/bitkey# git commit -m "commit new work"
[new-work 3b46e9a] commit new work
 1 file changed, 1 insertion(+)
 create mode 100644 some-work
root@tkldev products/bitkey# git checkout community 
Switched to branch 'community'
root@tkldev products/bitkey# git pull origin community 
From github.com:bitkey/bitkey
 * branch            community  -> FETCH_HEAD
Already up-to-date.
root@tkldev products/bitkey# git merge --no-ff new-work
Merge made by the 'recursive' strategy.
 some-work | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 some-work
root@tkldev products/bitkey# git push origin community
...
```
Hopefully that makes sense. 

Also FYI (in case you hadn't already realised) TKLDev includes some cool shortcuts by default. Check them out: `cat ~/.bashrc.d/git`

**Comment by estevaocm** [comment]
Thanks for the guidelines, @JedMeister . BTW, I was re-reading the development guidelines and remembered I have added a non-open source package into my Bitkey fork by request from one of our users. Namely, Exodus. Exodus has published some of its components as open source but not the full package. I think we should discuss whether to remove it or at least emphasize this issue in documentation.

**Comment by JedMeister** [comment]
Apologies on slow response @estevaocm. I hope I wasn't "[teaching you to suck eggs](https://en.wikipedia.org/wiki/Teaching_grandmother_to_suck_eggs)"! :smile: 

Whilst in theory, I'm not sure Alon and Liraz would be super enthused about any non-open source software being included, I'm personally not totally against it. However there are 2 main considerations:

 - Firstly, yes it should be clearly documented. Perhaps there should also be some way of removing it, or at least disabling it, during during boot for users who don't want/need it?

 - Secondly, we need to be careful about including proprietary software pre-installed as often there are licensing limitations on redistribution. So to ensure that we're not in breach of the license (and potentially also being in breach of GitHub policy, redistributing non-open source software), we'd need to carefully study it to ensure that we are being compliant. Because of the risk that the license may change between releases, really that needs to be done every time an updated release is added. AFAIK a license can only be updated with a new release, so while the software version stays the same, there probably isn't a need to do that for every BitKey release, just when a new version of the software is included. Because of that, it's often easier to just not include proprietary code and avoid the whole risk of DCMA takedown requests and/or nasty legal letters!
   - One way to work around redistribution licensing issues is to download and install on boot. Obviously that isn't much good for offline mode, but would be ok for online mode?

I'm totally open to further discussion on this.
