### ISSUE TITLE
Source code does not compile

### ISSUE THREAD

**Issue by dscoduc** [bitkey/bitkey#6]
I am unable to compile the source code due to what appears to be missing repositories.  Can you confirm that what's available on GitHub can be compiled?

**Comment by aidecoe** [comment]
I am trying to build latest bitkey from sources. I get:

```
E: Unable to locate package luks
E: Unable to locate package theme-zukitwo
```

which seems to be related to this bug. Do I need somehow point to these repositories?

**Comment by JedMeister** [comment]
Hi @aidecoe 
Thanks for the nudge. It has only relatively recently been updated and we haven't uploaded the newer packages to our archive yet. I will get onto Alon to upload the Jessie packages ASAP.

**Comment by aidecoe** [comment]
Thanks for prompt reply!

**Comment by lirazsiri** [comment]
For the record, building from source is currently working just fine.

**Comment by JedMeister** [comment]
Oops, I should have come back and closed this after Alon uploaded the updated packages to the TurnKey repo...
