### ISSUE TITLE
Monero, IOTA missing from ISO

### ISSUE THREAD

**Issue by quantumproducer** [bitkey/bitkey#63]
The Github talks about Monero & IOTA wallets. I installed the ISO, ran in cold-offline and I didn't see Monero, IOTA or Ethereum listed. All of the tools present were Bitcoin related (+ qr code, editor etc).

Is the ISO just behind the main build, or is there something else I have to do to run these programs in offline mode?

**Comment by estevaocm** [comment]
Please check the JavaScript apps.

**Comment by estevaocm** [comment]
http://estevao.altervista.org/bitcoin/offline-web-apps.png

**Comment by quantumproducer** [comment]
Thanks for the quick response @estevaocm .
Please excuse my ignorance, is that an option at the bottom toolbar at launch?
I do not see Offline Web Apps as an option in `turnkey-bitkey-14.2.0-jessie-amd64.ios` downloaded from the site.

**Comment by JedMeister** [comment]
@quantumproducer if you downloaded the ISO from https://bitkey.io/ then you don't have any of @estevaocm's goodies! To download the latest community ISOs (with all of @estevaocm's goodies, bugfixes and security updates) you need to download the ISOs from the [release page](https://github.com/bitkey/bitkey/releases).

We should probably update the website to make that clear. And actually seeing as the old version hosted there has a version of Electrum with reported security vulnerabilities (see #55), we probably should remove it altogether!

**Comment by quantumproducer** [comment]
@JedMeister wow.. glad I didn't do anything with the release yet. Please remove from the website! I'll try the Github release

**Comment by quantumproducer** [comment]
@JedMeister the release page lists 14.2.0-qrscan-altcoins-1.11-fixed beneath 1.11, but it has "Fixed" and "latest release" in it. I assume that's the correct one? I expected the latest release to be shown up top (maybe a quirk of Github)

**Comment by estevaocm** [comment]
@quantumproducer , that indeed is a quirk of Github. Apparently it is alphabetically ordered. It also does not give the exact time of the release, which makes it even more confusing. However, the one without "fixed" is 2 commits behind, and the fixed has no newer commits, so it's the latest version.

BTW, there are more commits in my personal fork at estevaocm/bitkey, but I'm still working on it so there is no release 1.12 yet.

**Comment by quantumproducer** [comment]
@estevaocm ah, thanks. 1.11 is gone now, "14.2.0-qrscan-altcoins-1.10" shows as the latest
(And by the way thank you for doing this work.. it's a great project)

**Comment by estevaocm** [comment]
I was releasing at estevaocm/bitkey until version 1.10. Now that I'm in the community branch here in bitkey/bitkey, I will be releasing only here. However, I work at estevaocm/bitkey first, doing commits and testing, and when a new version is ready, I make a pull request to merge my changes here and then build the new ISO.

**Comment by quantumproducer** [comment]
Thanks for the update!
