### ISSUE TITLE
List version number on Github page

### ISSUE THREAD

**Issue by quantumproducer** [bitkey/bitkey#64]
It isn't clear from the Github page if the ISO on the website is behind or not.
Fix: Show version number on Github

**Comment by JedMeister** [comment]
As per other comments I've made recently, if you downloaded from the website and have turnkey-bitkey-14.2.0-jessie-amd64.iso then you don't have @estevaocm's latest work. To get that, see the release page: https://github.com/bitkey/bitkey/releases

**Comment by quantumproducer** [comment]
Acknowledged
