### ISSUE TITLE
Armory Wallet Recovery

### ISSUE THREAD

**Issue by quantumproducer** [bitkey/bitkey#65]
Bitcoin Armory offers wallets with multi part keys.
I didn't see an option to import this way with Electrum in Bitkey.
I would like to see Bitcoin Armory included in Bitkey.

**Comment by aghamir** [comment]
Also omniwallet offline transaction works with Armory.

**Comment by quantumproducer** [comment]
Potential PR: https://github.com/bitkey/bitkey/pull/71

**Comment by estevaocm** [comment]
PR accepted. I will release a new binary as soon as I am able to test this new version and update other packages such as Electrum.
