### ISSUE TITLE
Signing Offline TX Without Electrum

### ISSUE THREAD

**Issue by quantumproducer** [bitkey/bitkey#67]
Hi, I am looking on how to sign an offline transaction without using Electrum, which requires USB storage.

What I am looking for is

> Enter private key
> Enter destination address
> Create transaction
> Sign transaction
> Transfer transaction to online computer + publish .

Is this possible with the latest community release of Bitkey?

I tried using CoinBin to New > Transaction, but it wants "inputs" and it's not clear how to use those. I tried the other tools and didn't see a way.

Please advise, thank you!

**Comment by estevaocm** [comment]
I personally only use Electrum. But you don't really need storage to use it. You may, instead, run "electrum" from the terminal to bypass the wrapper (which requires storage). Then you may create a temporary wallet in the virtual filesystem using the private key you already have.

**Comment by quantumproducer** [comment]
Oh thanks, I didn't realize command line Electrum was an option!
Looks like http://docs.electrum.org/en/latest/coldstorage_cmdline.html is how to do that. I will try

**Comment by quantumproducer** [comment]
@estevaocm so it looks like that is an option.. I need to read more about how `electrum importprivkey` works.

By the way, this might be a seperate issue -- I tried running Electrum and creating a new wallet importing from a key it says "Type a list of addresses or list of private keys"

If I type the address shown by a couple of the offline web tools, I get a watching only wallet.

IIf I got back to that screen and type private key, the next button never becomes available.

When Electrum is running, there is no option under Private Keys to Import, only Sweep or Export.
Is this expected? Maybe I'm missing something here

**Comment by quantumproducer** [comment]
Ah, hm. https://bitcointalk.org/index.php?topic=1970345.0
"There is no import function in Electrum anymore, only sweeping"
Hm. I was hoping to 
> enter private key into Electrum
> verify my receiving address matches what the other offline tools generated
> send BTC to this address

**Comment by quantumproducer** [comment]
@estevaocm `electrum listaddresses` gives an error:  ~"can't use cmdline_run "

I figured out the private key Electrum wants is a WIF, derived from the hex. So I use one of the offline tools to get a WIF. I enter that into Electrum. It shows 1 Receiving address, which matches what I have previously generated.

So far so good.

Now I import another Electrum wallet with funds. I enter the new Receiving address as destination + an amount. When I click "Preview" or "Send", I get "Insufficient Balance". 

I expected to create a TX, sign & save that TX file, unplug my USB, insert TX transfer USB, copy TX to transfer USB, move to online computer, broadcast.

Then in the future I could send the same way from the Receiving address - creating an offline transaction, etc.

Reading https://bitcoin.stackexchange.com/questions/72757/how-to-create-a-valid-unsigned-transaction/72760#72760 talks about how TXs must be spent from UTXos, which now makes more sense why one of the offline tools (coinbin I think) had "inputs" as a requirement, including transaction ID.

https://www.turnkeylinux.org/blog/secure-bitcoin-transactions#kill-bitkey describes what sounds like a very easy process..

I would like to know if there's a guide that shows exactly how to do this, or how to do what I thought you could do above^?

**Comment by quantumproducer** [comment]
I see now, you have to create watching address with Electrum on online computer or another tool to get the inputs. Sorry for the bogus issue!

**Comment by estevaocm** [comment]
Glad to help. Good for you for figuring it out yourself from a few tips.
