### ISSUE TITLE
Feature request: memory-only wallets

### ISSUE THREAD

**Issue by UnoMamiko** [bitkey/bitkey#7]
User enters a seed, wallet is created in memory only, never written to disk. User closes electrum, the wallet disappears. It's a brain wallet.

I just [posted this request to the electrum issue tracker](https://github.com/spesmilo/electrum/issues/781). Don't know whether they will see it as an issue that should be handled by the app (electrum) or not. There is the argument that things like this should be handled by the OS, in which case bitkey could implement it.

**Comment by lirazsiri** [comment]
Easiest way to store wallet in memory is to launch electrum from a terminal like this:

```
electrum -w /tmp/brainwallet
```

Then restore the wallet and import the private key. I documented this in the README.
