### ISSUE TITLE
Bus Error when launching apps

### ISSUE THREAD

**Issue by techboss** [bitkey/bitkey#80]
I just did a build of the latest community branch and can't start Electrum (or most other apps for that matter) from the launch bar on an air-gapped Dell Latitude laptop.  When I start Electrum from the command line with verbose mode switch I see it roll through trying to contact a few hosts and then terminate with a "Bus error" message.  I am able to launch the Electrum daemon (no GUI) from the command line.

An older pre-built version of the Bitkey ISO (with Electrum 2.9.4) works ok on that laptop along with other linux distros so I don't think there is a hardware problem, but community ISO I built seems to work ok in a VM on my Mac.

Any ideas?

**Comment by estevaocm** [comment]
If you built it yourself, the problem may be that Turnkey has been upgraded but Bitkey hasn't adjusted yet. Does the latest pre-built ISO fail as well?

**Comment by techboss** [comment]
I tested my build on a different laptop today (HP) and got the same "Bus Error" message so I don't think it's hardware.  I'll test the latest pre-built ISO this weekend.

**Comment by techboss** [comment]
I just downloaded the pre-built ISO and it's the same as the one I already had (turnkey-bitkey-14.2.0-jessie-amd64.iso) which worked fine except that Electrum 2.9.4 has a known bug and gets stuck syncronizing.  What version of Turnkey should I use to build the latest Community branch?

**Comment by estevaocm** [comment]
I'd suggest you try this version first: https://github.com/bitkey/bitkey/releases/latest

Upgrading Bitkey is discussed in https://github.com/bitkey/bitkey/issues/74 and https://github.com/bitkey/bitkey/issues/73

**Comment by techboss** [comment]
Thanks - much appreciated.  I've got some cycles to spare, like the project and want to contribute.  Where's a good place to start?

**Comment by estevaocm** [comment]
Right now my development workspace is on hold until I figure out the Turnkey upgrade, but I haven't had dedicated time for that lately. As @JedMeister explains in those issues I mentioned, there are a number of package and build adjustments to get Bitkey to run on Turnkey 15. Any help at that front could get me back on track sooner. If you want to give it a try, you might log your progress in the respective issues so we can follow up. Thanks!

**Comment by techboss** [comment]
@estevaocm thanks for the pointers - I got the community build to work.
