### ISSUE TITLE
Electrum fails to load transactions

### ISSUE THREAD

**Issue by vitork** [bitkey/bitkey#81]
Electrum v3.1.2 is failing to load transactions created by Electrum v3.2.2 on an online machine. Similar to #70, this makes it impossible to sign transactions within Bitkey cold-offline mode.

I've played around here and found out that the solution would be to update Electrum to the latest version v3.2.2 on BitKey. I'll attach a PR to this fix in a few moments.

**Comment by estevaocm** [comment]
Thank you for your PR, unfortunately my build environment is messed up by the Debian-stretch upgrade attempt and I won't be able to test the merge and build an ISO right now. I'll get back to this as soon as I can.

**Comment by estevaocm** [comment]
You may try the alpha build at https://github.com/estevaocm/bitkey/releases/tag/15.0.0-stretch-alpha2-community

There are issues, development is ongoing.
