### ISSUE TITLE
Electrum fails to load transactions

### ISSUE THREAD

**Issue by nextgenthemes** [bitkey/bitkey#84]
I am aware there is another issue but I actually DO get a error message while trying to load from file or text.

`unable to deserialize the transaction: unpack_from requires a buffer of at least 4 bytes`

**Comment by brincobt** [comment]
In Bitkey Electrum should be upgraded to  v3.2.3
Cold offline mode is unable to sign transactions created from Electrum v3.2.2 and up.

**Comment by tuberculo** [comment]
Is there an open issue about that in Electrum Github?

**Comment by LF76** [comment]
It's because of this upgrade: https://github.com/spesmilo/electrum/blob/3.2.2/RELEASE-NOTES#L30-L34

 * The partial transaction format has been incompatibly changed. This
   was needed as for partial transactions the scriptSig/witness has to
   be parsed, but for signed transactions we did not want to do the
   parsing.  Users should make sure that all instances of Electrum
   they use to co-sign or offline sign, are updated together.

**Comment by estevaocm** [comment]
Sorry, I'm currently held back by the Debian-stretch upgrade. Haven't been successful so far. I'll see if the jesse builds are still possible for these application updates when I have time.

**Comment by JedMeister** [comment]
**[OT]** @estevaocm - apologies on the hold up on my end... I've had a little bit more of a look but still can't work out what is going on. I'll probably need to a serial connection so I can see what is actually going wrong at boot... And I've been pretty snowed under with other stuff. But I'll aim to have more of a look early next week.

**Comment by LF76** [comment]
As a quick workaround, you can keep the latest Electrum v3.2.3 installed, and use the portable v3.1.3 version from https://download.electrum.org/3.1.3/ in a separate folder (with the Xpub (read-only mode)). Then use this version to generate the transaction, and sign it in Bitkey (in the cold-offline mode).

**Comment by nextgenthemes** [comment]
Where there not important security fixes? I really do not feel comfortable downgrading. Really disappointed the wallet is not just updated in the community iso. I think there is already a RP for this.

I guess its possible to download the latest (to a separate or shuttle USB) and replace/use it on the booted outdated iso. I would rather do that instead of downgrading.

**Comment by estevaocm** [comment]
@nextgenthemes, all work here is voluntary. This is an open source project, so feel free to fork and build your own ISO if the provided one is not up to your expectations. As explained, we are in the process of upgrading the Debian OS and don't have the manpower to tackle each and every user issue. And you could easily insert any version of Electrum or any other wallet you'd like to use by USB. This has already been suggested in previous issues.

**Comment by nextgenthemes** [comment]
Well this is not "each and every user issue" its a pretty severe issue makes the very base function of this totally unusable. I have read that you messed up your build env so there is nobody who can build the ISO based on the PR and release it? Why does the big Debian update have to come first if this totally breaks everything?

**Comment by estevaocm** [comment]
Nothing is unusable. This is a cold wallet. It is designed to be secure. The supported Electrum version is declared in the release notes. If you want to use another version, either do the work yourself or wait until a new build is ready.

**Comment by estevaocm** [comment]
BTW, by reading Electrum's release notes, the newer versions are mostly feature releases, not security fixes.

**Comment by estevaocm** [comment]
There is yet another problem. The newer releases of Electrum and its derivatives requires Python3, which is not available in Debian Jessie repositories. So either it has to be manually installed on Jessie, which is not as straightforward as it sounds, or ideally Bitkey would be upgraded to Debian Stretch and Python3 installed by its repositories. Both options have been taking a lot of time.

**Comment by estevaocm** [comment]
I am uploading an alpha version of Bitkey Stretch with the latest Electrum at https://github.com/estevaocm/bitkey/releases/tag/15.0.0-stretch-alpha2-community

Further Bitkey 15 development is still required to restore the full original functionality.
