### ISSUE TITLE
Electrum v3.3.3

### ISSUE THREAD

**Issue by aghamir** [bitkey/bitkey#87]
Hi,
I know you are busy to build bitkey on debian/stretch. However, is it possible now to upgrade electrum? The client(online one) cannot be in lower version due to security issue(phishing).

**Comment by estevaocm** [comment]
Thank you for your request. There should be no risk of phishing as long as you don't agree to install a new software, which you should never do within Bitkey and probably wouldn't have permission anyway.

**Comment by aghamir** [comment]
Of course there isn't any thread for bitkey in this issue. However, electrum client in online computer is forced to update due to this issue(electrum does). So, making transaction with updated client is not possible by this state. 
I understand it's too hard to update electrum at this moment due to debian-stretch update and I will appreciated it. Probably I will use PR #82 to update electrum.

**Comment by estevaocm** [comment]
I see. The stretch release was supposed to be ready by this point, but a critical dependency is missing in the repos and we're still trying to get alternatives to work. Currently I have no setup for the jessie version, otherwise I could provide an update within an hour.

**Comment by estevaocm** [comment]
Unfortunately, everything seems to be working against Bitkey. Electrum development is moving fast and Bitkey is not keeping up. The current Electrum version "requires Python version >= 3.6.1". This version is not available in the Turnkey Debian Jessie and Stretch repositories so it will have to be installed manually in Bitkey, which is not as simple as it seemed at first. I was close to achieving this in the Jessie build but it never really worked. And on top of all of this, USB is not working.

I will try to get Electrum to work by installing the latest Python, but this will take a while. At least then users will be able to manually recreate their wallets through their mnemonic seeds and operate. But I have to admit this whole situation is quite upsetting.

**Comment by estevaocm** [comment]
Good news, I got Python 3.7.2 to work in Bitkey and now the latest Electrum, Electrum-LTC and Electron-Cash run succesfully. Although I haven't yet tested operating wallets on them, and I had to disable keepassxc in order to achieve this build. USB is still not working.

**Comment by estevaocm** [comment]
I am uploading the ISO for this alpha build at https://github.com/estevaocm/bitkey/releases/tag/15.0.0-stretch-alpha2-community

Known issues are documented at the release page. Should at least allow minimal use for now.
