### ISSUE TITLE
Failed to build Bitkey from source, VMware + turnkey-tkldev-14.2-jessie-amd64

### ISSUE THREAD

**Issue by QuantBox723** [bitkey/bitkey#88]
Trying to build from sources using VMware + turnkey-tkldev-14.2-jessie-amd64:

ssh tkldev
cd products
git-clone --depth 1 https://github.com/bitkey/bitkey
cd bitkey
make

At the end the build process is stopped at the following error message:

[...]
 extracting: /usr/local/share/electrum-dash/packages/x11_hash-1.4.egg-info/top_level.txt
  inflating: /usr/local/share/electrum-dash/packages/x11_hash.so
   creating: /usr/local/share/electrum-dash/packages/_markerlib/
  inflating: /usr/local/share/electrum-dash/packages/_markerlib/markers.py
  inflating: /usr/local/share/electrum-dash/packages/_markerlib/markers.pyc
  inflating: /usr/local/share/electrum-dash/packages/_markerlib/__init__.py
  inflating: /usr/local/share/electrum-dash/packages/_markerlib/__init__.pyc
sudo: unable to resolve host tkldev
sudo: unable to resolve host tkldev
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
error in trezor setup command: Invalid environment marker: python_version < "3.5"
/usr/share/fab/product.mk:526: recipe for target 'build/stamps/root.patched' failed
make: *** [build/stamps/root.patched] Error 1

Any ideas what went wrong here? 
What does "sudo: unable to resolve host tkldev" mean?

**Comment by estevaocm** [comment]
I'm not sure it is still possible to build the Jessie version due to Turnkey having been migrated to Stretch. @JedMeister probably can clarify. I have began migrating Bitkey to Stretch but haven't got around the USB support. You may verify this version at https://github.com/estevaocm/bitkey/tree/stretch
