### ISSUE TITLE
Make does not work anymore

### ISSUE THREAD

**Issue by glenavery** [bitkey/bitkey#89]
I created a new TKLDEV image and successfully run a build of core on it. When I tried to make bitkey however I get the following errors. I am a beginner at this so any help is appreciated. I would like to update Electrum as the current version in bitkey is too old and no longer works.

root@tkldev ~/products/bitkey# make
if ! deck --isdeck build/root.build; then deck build/bootstrap build/root.build; fi
fab-chroot build/root.build --script conf.d/preseeds
fab-install build/root.build build/root.spec
setting apt proxy settings...
updating package lists...
Hit:1 http://security-cdn.debian.org stretch/updates InRelease
Ign:3 http://archive.turnkeylinux.org/debian stretch-security InRelease
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Ign:4 http://archive.turnkeylinux.org/debian stretch InRelease
Hit:5 http://cdn-fastly.deb.debian.org/debian stretch Release
Hit:6 http://archive.turnkeylinux.org/debian stretch-security Release
Hit:9 http://archive.turnkeylinux.org/debian stretch Release
Reading package lists... Done
installing packages...
Reading package lists... Done
Building dependency tree
Reading state information... Done
linux-image-amd64 is already the newest version (4.9+80+deb9u7).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package myspell-en-us is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  hunspell-en-us

E: Unable to locate package luks
E: Package 'myspell-en-us' has no installation candidate
E: Unable to locate package theme-zukitwo
E: Unable to locate package usbmount
Traceback (most recent call last):
  File "/usr/lib/fab/wrapper.py", line 34, in <module>
    CliWrapper.main()
  File "/usr/lib/python2.7/dist-packages/pyproject.py", line 388, in main
    commands.run(name, args)
  File "/usr/lib/python2.7/dist-packages/pyproject.py", line 261, in run
    command.module.main()
  File "/usr/lib/fab/pylib/cmd_install.py", line 129, in main
    installer.install(packages, ignore_errors)
  File "/usr/lib/fab/pylib/installer.py", line 267, in install
    self._install(packages, ignore_errors)
  File "/usr/lib/fab/pylib/installer.py", line 137, in _install
    self.chroot.system("apt-get", *(args + packages))
  File "/usr/lib/python2.7/dist-packages/chroot.py", line 80, in system
    executil.system(*self._prepare_command(*command))
  File "/usr/lib/python2.7/dist-packages/executil.py", line 56, in system
    raise ExecError(command, exitcode)
executil.ExecError: non-zero exitcode (100) for command: chroot '/root/products/bitkey/build/root.build'  'sh'  '-c'  "env -i  'TERM=xterm-256color'  'AMD64=y'  'DEBIAN_FRONTEND=noninteractive'  'HOSTNAME=bitkey'  'FAB_ARCH=amd64'  'DEBIAN=y'  'FAB_HTTP_PROXY=http://127.0.0.1:8124'  'NONFREE=yes'  'DEBIAN_PRIORITY=critical'  'HOME=/root'  'RELEASE=debian/stretch'  'PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/bin:/usr/sbin'  'CODENAME=stretch'  'LC_ALL=C'  'DISTRO=debian' apt-get 'install'  '--force-yes'  '--assume-yes'  'libgcc1'  'busybox'  'hostname'  'bsdutils'  'lsb-base'  'wpasupplicant'  'laptop-detect'  'iproute'  'cups-browsed'  'passwd'  'findutils'  'casper'  'libsemanage-common'  'sensible-utils'  'systemd'  'util-linux'  'libncursesw5'  'libsystemd0'  'mdetect'  'whiptail'  'wbar'  'printer-driver-brlaser'  'thunar'  'dconf-tools'  'p7zip-full'  'sysv-rc'  'consolekit'  'locales'  'avahi-daemon'  'bind9-host'  'console-setup'  'printer-driver-gutenprint'  'iptables'  'python-setuptools'  'libpam-modules'  'python-qt4'  'inputattach'  'liblzma5'  'xterm'  'firmware-ipw2x00'  'cpio'  'bash-completion'  'libqt5x11extras5'  'ca-certificates'  'libacl1'  'debian-archive-keyring'  'startpar'  'libncurses5'  'printer-driver-c2050'  'libgpg-error0'  'libkmod2'  'libpam0g'  'luks'  'python-psutil'  'system-config-printer'  'libpam-modules-bin'  'printer-driver-splix'  'patch'  'psmisc'  'e2fslibs'  'net-tools'  'gcc-6-base'  'libglib2.0-bin'  'debconf'  'sysvinit-utils'  'rsyslog'  'adduser'  'syslinux-common'  'dosfstools'  'libudev1'  'discover'  'udev'  'firmware-linux-free'  'sed'  'printer-driver-c2esp'  'gnome-tweak-tool'  'mktemp'  'kmod'  'libperl4-corelibs-perl'  'localepurge'  'isolinux'  'libselinux1'  'openprinting-ppds'  'autocutsel'  'ncurses-bin'  'printer-driver-min12xxw'  'read-edid'  'wicd'  'libsmartcols1'  'printer-driver-hpijs'  'firmware-atheros'  'libpam-runtime'  'libss2'  'firmware-realtek'  'libpcre3'  'printer-driver-m2300w'  'at-spi2-core'  'libdebconfclient0'  'libmount1'  'libattr1'  'hp-ppd'  'florence'  'systemd-sysv'  'wget'  'printer-driver-foo2zjs'  'firmware-bnx2x'  'pyqt4-dev-tools'  'bash'  'mawk'  'dmidecode'  'ethtool'  'hplip'  'pcmciautils'  'python-dialog'  'printer-driver-sag-gdi'  'pmount'  'login'  'lsof'  'task-print-server'  'linux-base'  'libklibc'  'cheese'  'firmware-bnx2'  'gpgv'  'printer-driver-escpr'  'apt'  'feh'  'chromium'  'init-system-helpers'  'libc-bin'  'syslinux'  'ifupdown'  'dmz-cursor-theme'  'ntpdate'  'liblz4-1'  'vim-gtk'  'keepassx'  'firmware-libertas'  'netbase'  'libaudit-common'  'firmware-linux-nonfree'  'turnkey-sysinfo'  'x11-common'  'dash'  'libc-l10n'  'klibc-utils'  'libsepol1'  'traceroute'  'turnkey-version'  'libsemanage1'  'firmware-ralink'  'hdparm'  'debianutils'  'printer-driver-pnm2ppa'  'myspell-en-us'  'ncurses-base'  'diffutils'  'dpkg'  'iputils-ping'  'pyqt5-dev-tools'  'firmware-brcm80211'  'grep'  'eject'  'mount'  'python3-pyqt5'  'printer-driver-hpcups'  'initscripts'  'libdb5.3'  'gnupg'  'libapt-pkg5.0'  'python3-setuptools'  'procps'  'printer-driver-cjet'  'libykpers-1-1'  'zbar-tools'  'turnkey-pylib'  'pinentry-gtk2'  'theme-zukitwo'  'sudo'  'xkb-data'  'secure-delete'  'gnupg-agent'  'unzip'  'foomatic-db-engine'  'libprocps6'  'base-files'  'printer-driver-postscript-hp'  'curl'  'tar'  'initramfs-tools'  'libtinfo5'  'printer-driver-pxljr'  'libfdisk1'  'python-sip'  'libgconf-2-4'  'libaudit1'  'coreutils'  'metacity'  'lsb-release'  'libstdc++6'  'mrxvt'  'gvfs'  'dbus-x11'  'printer-driver-dymo'  'libusb-1.0-0-dev'  'initramfs-tools-core'  'wireless-tools'  'libbz2-1.0'  'insserv'  'less'  'libcap-ng0'  'multiarch-support'  'policykit-1'  'zlib1g'  'xorg'  'libc6'  'qtqr'  'libustr-1.0-1'  'thunar-volman'  'libpam-ck-connector'  'libcomerr2'  'libgcrypt20'  'usbmount'  'inithooks'  'isc-dhcp-client'  'usbutils'  'e2fsprogs'  'libuuid1'  'perl-base'  'firmware-iwlwifi'  'pciutils'  'gzip'  'printer-driver-ptouch'  'libblkid1'  'base-passwd'"
/usr/share/fab/product.mk:535: recipe for target 'build/stamps/root.build' failed
make: *** [build/stamps/root.build] Error 1
root@tkldev ~/products/bitkey#

**Comment by estevaocm** [comment]
This version works: https://github.com/estevaocm/bitkey/

But there are still several pending issues from migration to debian stretch.

**Comment by tuberculo** [comment]
Hi @estevaocm. What are the issues in that version? Does it work to sign transactions from current electrum version?

**Comment by estevaocm** [comment]
Hello @tuberculo. The complete release notes are at https://github.com/estevaocm/bitkey/releases/tag/15.0.0-alpha-stretch-community along with a binary.

**Comment by estevaocm** [comment]
It seems the tag was applied to the wrong branch. The latest source could should be this branch: https://github.com/estevaocm/bitkey/tree/stretch

**Comment by estevaocm** [comment]
This issue is tracked here: https://github.com/bitkey/bitkey/issues/74
